### ISSUE TITLE
Crashes on Windows 8.1

### ISSUE THREAD

**Issue by casbreuk** [kode54/vstdriver#2]
Hey guys!
Any chance you'll update this to work without crashing on Win8.1?

I've got it installed at work, and it's fine until I run visual studio.  Then it crashes (vstmididrv.dll causes an exception and crashes winhost).  It also only somewhat works when it does.  Instead of being system-wide, it works only in winamp (until the crash) and not WMP.  At home, on Windows 8.0, it only seems to work in WMP and not winamp.  It's the weirdest thing.  I also find that I need to use a 3rd party midi device switcher since the built-in one isn't working very well, if at all.
64-bit windows

Steps to install:
Uninstall old version.
Install new one.
Give vsthost64.exe admin permissions, as well as vsthost.exe
Reboot twice.  It's already set to use my Yamaha SY-XG50 synth files (which I've used for years with this vst driver)

**Comment by mudlord** [comment]
WMP uses a certain registry key. I need to work out what registry key it is. to fix that problem. I noticed no crashing problems on my setup.

**Comment by kode54** [comment]
Is this bug still relevant to the latest release? I do not have Windows 8.1 handy to test, but I could be bothered to at least try installing it in a virtual machine.

**Comment by KaleidonKep99** [comment]
It does work under 8.1.
