### ISSUE TITLE
Pitch issues under Windows 10

### ISSUE THREAD

**Issue by KaleidonKep99** [kode54/vstdriver#5]
VSTi Driver seems to have the wrong pitch, under Windows 10.
It happens with every VST I tried on it.

Here are some tests with S-YXG50.

How it's supposed to sound like, on Foobar2000: https://youtu.be/jOIJDNZSXyQ
How it actually sounds like, through VST MIDI Driver: https://youtu.be/s8axI9frrhk

It doesn't happen under previous versions of Windows.

**Comment by kode54** [comment]
Known, I need to fix the WASAPI interface to be like the Secret Sauce and BASSMIDI drivers. Basically, WASAPI doesn't let you set the sample rate, you open the output, ask it what sample rate to play at, and configure the driver accordingly.

**Comment by kode54** [comment]
This should be fixed by the new release I uploaded.

**Comment by KaleidonKep99** [comment]
It works! Thanks Kode. 😀
